# Generated by Django 3.2.13 on 2022-07-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_year',
            field=models.CharField(default='', max_length=2),
        ),
    ]
