# Generated by Django 3.2.13 on 2022-07-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='listed_by',
            new_name='product_listed_by',
        ),
    ]
