# Generated by Django 3.2.13 on 2022-07-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220701_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
