# Generated by Django 3.2.13 on 2022-07-01 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='product_owner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
