# Generated by Django 3.2.13 on 2022-07-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_query_product_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
